### ISSUE TITLE
请问为何不建议将 FPKM 矩阵转换到 TPM？

### ISSUE THREAD

**Issue by ieiwk** [MatthewP-Newbee/GdcData#1]
如题。谢谢！

**Comment by MatthewP-Newbee** [comment]
因为只看公式似乎可以转换，可是实际软件处理有更多的其他处理。首先本身的概念 TPM 是 Transcript per million 基于转录本，而 FPKM 是 reads/fragments per kilobase of exon per million reads/fragments mapped 基于外显子，转录本和外显子的关系是复杂的，从这个角度来说我们不应该进行 2 者转换，因为 2 者概念不具备简单的可比性。
[这里](https://docs.gdc.cancer.gov/Encyclopedia/pages/HTSeq-FPKM/) 和 [这里](https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline/) 是 GDC 计算 FPKM 公式，他明确 reads 总数目是比对到外显子的 reads 数。
另外我也试过直接用公式转换 TPM ，然后实际处理发现数据的分布就变得很奇怪，所以我觉得应该是转换导致的问题。
一家之言，欢迎讨论。

**Comment by ieiwk** [comment]
谢谢答复！

第二个链接里涉及了exon。L: Length of the gene in base pairs; Calculated as the sum of all exons in a gene。但the sum of all exons in a gene不就差不多相当于该基因的转录本的长度么？

不过我们也有点感觉FPKM比TPM好用。基于FPKM的一个TCGA生存分析是很显著的，用TPM时就没有了。

**Comment by MatthewP-Newbee** [comment]
[这篇文章](https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html) 讲解 RNA-seq 差异基因的比较挺不错，可以了解一下。

**Comment by ieiwk** [comment]
> [这篇文章](https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html) 讲解 RNA-seq 差异基因的比较挺不错，可以了解一下。

感谢分享。正在断断续续地读。
